language: rust
sudo: required
os:
- linux
- osx
rust:
- stable
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
script:
- cargo test
- cargo build
