[package]
name = "compose_yml"
version = "0.0.55"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

description = "Parse, manipulate and serialize docker-compose.yml in a strongly-typed fashion"
documentation = "http://docs.rs/compose_yml"
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/emk/compose_yml"

[dependencies]
clippy = { version = ">=0", optional = true }
error-chain = ">=0"
lazy_static = ">=1"
log = ">=0"
regex = ">=0"
serde = ">=1"
serde_derive = ">=1"
serde_json = ">=1"
serde_yaml = ">=0"
yaml-rust = ">=0"
url = ">=1"
valico = ">=1"
void = ">=1"
