[package]
name = "compose_yml"
version = "0.0.57"
authors = ["Eric Kidd <git@randomhacks.net>"]
edition = "2018"

description = "Parse, manipulate and serialize docker-compose.yml in a strongly-typed fashion"
documentation = "http://docs.rs/compose_yml"
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/emk/compose_yml"

[dependencies]
clippy = { version = ">=0", optional = true }
error-chain = ">=0.12.1"
lazy_static = ">=1.3.0"
log = ">=0.4.7"
regex = ">=1.2.0"
serde = ">=1.0.97"
serde_derive = ">=1.0.97"
serde_json = ">=1.0.40"
serde_yaml = ">=0.8.9"
yaml-rust = ">=0.4.3"
url = ">=1.7.2"
valico = ">=3.0.0"
void = ">=1.0.2"
