[package]
name = "docker_compose"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]
build = "build.rs"

[features]
default = ["serde_codegen"]
unstable = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_macros = { version = "0.8", optional = true }
serde_yaml = "0.4.0"
yaml-rust = "0.3.3"

