[package]
name = "compose_yml"
version = "0.0.41"
authors = ["Eric Kidd <git@randomhacks.net>"]
build = "build.rs"

description = "Parse, manipulate and serialize docker-compose.yml in a strongly-typed fashion"
documentation = "http://docs.randomhacks.net/compose_yml/"
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/emk/compose_yml"

[features]
default = ["glob", "serde_codegen"]
unstable = ["serde_macros", "clippy"]

[build-dependencies]
glob = { version = "0.2.11", optional = true }
serde_codegen = { version = "0.8", optional = true }

[dependencies]
clippy = { version = "0.*", optional = true }
error-chain = "0.5.0"
lazy_static = "0.2.1"
log = "0.3.6"
regex = "0.1.73"
serde = "0.8"
serde_macros = { version = "0.8", optional = true }
serde_yaml = "0.4.0"
yaml-rust = "0.3.3"
url = "1.2.0"
void = "1.0.2"
